### ISSUE TITLE
Doesn't work with WP 4.7

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/imagga#10]
@cristian-ungureanu @selul The plugin doesn't work with WP 4.7 

We do not have any error, but he can't add tags.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu what do you think here? it would take a lot to fix this? because if it would take a long time, we can give up for moment

**Comment by cristian-ungureanu** [comment]
@mileamadalin , @rodica-andronache the api doesn't always returns a response so it may seem it doesn't work but if you try with another photo, you'll get your tags. Tested on mystock and it works just fine.
