### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/imagga#11]
@cristian-ungureanu someone reported here that the tagging doesn't seem to be working.
I tested too and I got the same result. 
https://secure.helpscout.net/conversation/504466756/152132/?folderId=265052

From what I've seen, I think it might be related to this check https://github.com/Codeinwp/imagga/blob/production/admin/class-imagga-admin.php#L233 as I think get_post_meta is returning an array, unless you add a third true parameter , 
plus I think you need to use https for the curl request https://github.com/Codeinwp/imagga/blob/production/admin/class-imagga-admin.php#L245

When you have some time, you can have a look on this 👍

**Comment by cristian-ungureanu** [comment]
The issue was fixed and also added a new feature to support custom post types.
